### ISSUE TITLE
Broken dependency

### ISSUE THREAD

**Issue by fvilante** [ameerthehacker/cli-spinners#2]
Is there a way to solve this broken dependency?

Tryed on Deno 0.13.0 and 0.18.0 and got the same error.

Thanks!

**Test Code**

```typescript
import Spinner from 'https://raw.githubusercontent.com/ameerthehacker/cli-spinners/master/mod.ts';

const spinner = Spinner.getInstance();

spinner.start('running step 1');
// Perform long running step 1
spinner.setText('running step 2');
// Perform long running step 2
spinner.stop();
```

**Output result**

```
> deno run spinner.ts
Compile file:///C:/temp/deno-play/spinner.ts
Download https://deno.land/x/std/colors/mod.ts
error: Uncaught Other: Import 'https://deno.land/x/std/colors/mod.ts' failed: 404 Not Found
► file:///C:/deno/js/dispatch_json.ts:40:11
    at DenoError (file:///C:/deno/js/errors.ts:20:5)
    at unwrapResponse (file:///C:/deno/js/dispatch_json.ts:40:11)
    at sendSync (file:///C:/deno/js/dispatch_json.ts:67:10)
    at fetchSourceFile (file:///C:/deno/js/compiler.ts:142:15)
    at _resolveModule (file:///C:/deno/js/compiler.ts:243:24)
    at file:///C:/deno/js/compiler.ts:381:33
    at resolveModuleNames (file:///C:/deno/js/compiler.ts:374:24)
    at resolveModuleNamesWorker (typescript.js:89230:127)
    at resolveModuleNamesReusingOldState (typescript.js:89473:24)
    at processImportedModules (typescript.js:90812:35)
```

**Comment by ameerthehacker** [comment]
Hi @fvilante I will look into it, please feel free to make a PR if you already have!

**Comment by ameerthehacker** [comment]
It had been fixed, please try and let me know. If you still have any difficulties please feel free to create a new issue
